version: '3.8'

services:
  hirenetic-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hirenetic_scripts_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
