-- ==========================================================
-- Table: crwl_jobsData
-- ==========================================================

CREATE TABLE public."crwl_jobsData" (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Source Information
    source VARCHAR(50) NOT NULL,
    source_company VARCHAR(255),
    external_job_id VARCHAR(255) NOT NULL,

    -- Job Details
    title VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    department VARCHAR(150),

    employment_type VARCHAR(50),
    workplace_type VARCHAR(50),
    experience_level VARCHAR(100),

    -- Location
    location VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),

    -- Salary
    salary_min NUMERIC(12,2),
    salary_max NUMERIC(12,2),
    salary_currency VARCHAR(10),

    -- Job Content
    description TEXT,
    requirements TEXT,
    responsibilities TEXT,
    benefits TEXT,

    -- Structured Data
    skills JSONB DEFAULT '[]'::jsonb,
    education VARCHAR(150),
    experience_years INTEGER,

    -- URLs
    apply_url TEXT,
    job_url TEXT,
    company_logo TEXT,
    company_website TEXT,

    -- Dates
    posted_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    first_seen_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW(),
    crawled_at TIMESTAMPTZ DEFAULT NOW(),

    -- Status
    status VARCHAR(20) DEFAULT 'Active',
    is_active BOOLEAN DEFAULT TRUE,

    -- Duplicate Detection
    hash VARCHAR(64),

    -- AI Fields
    ai_summary TEXT,
    ai_tags JSONB DEFAULT '[]'::jsonb,

    -- Audit
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT uq_source_external_job UNIQUE (source, external_job_id)
);

-- ==========================================================
-- Indexes
-- ==========================================================

CREATE INDEX idx_jobs_source
ON public."crwl_jobsData"(source);

CREATE INDEX idx_jobs_company
ON public."crwl_jobsData"(company_name);

CREATE INDEX idx_jobs_title
ON public."crwl_jobsData"(title);

CREATE INDEX idx_jobs_location
ON public."crwl_jobsData"(location);

CREATE INDEX idx_jobs_posted
ON public."crwl_jobsData"(posted_at DESC);

CREATE INDEX idx_jobs_status
ON public."crwl_jobsData"(status);

CREATE INDEX idx_jobs_active
ON public."crwl_jobsData"(is_active);

CREATE INDEX idx_jobs_hash
ON public."crwl_jobsData"(hash);

CREATE INDEX idx_jobs_skills
ON public."crwl_jobsData"
USING GIN (skills);

CREATE INDEX idx_jobs_ai_tags
ON public."crwl_jobsData"
USING GIN (ai_tags);

-- ==========================================================
-- Auto-update updated_at
-- ==========================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_crwl_jobsData_updated_at
BEFORE UPDATE ON public."crwl_jobsData"
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();