-- ========================================================
-- Table: scriptsEditor
-- Description: Stores all automated & custom scripts for Hirenetic Scripts Inventory
-- ========================================================

CREATE TABLE IF NOT EXISTS public."scriptsEditor" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    filename TEXT NOT NULL,
    category TEXT DEFAULT 'Resume',
    description TEXT,
    status TEXT DEFAULT 'Active',
    locked BOOLEAN DEFAULT FALSE,
    password TEXT DEFAULT NULL,
    created DATE DEFAULT CURRENT_DATE,
    code TEXT,
    executions INTEGER DEFAULT 0
);

-- Enable Row Level Security (RLS)
ALTER TABLE public."scriptsEditor" ENABLE ROW LEVEL SECURITY;

-- Allow public read access (SELECT)
CREATE POLICY "Allow public read access on scriptsEditor" 
    ON public."scriptsEditor" 
    FOR SELECT 
    USING (true);

-- Allow public insert access (INSERT)
CREATE POLICY "Allow public insert access on scriptsEditor" 
    ON public."scriptsEditor" 
    FOR INSERT 
    WITH CHECK (true);

-- Allow public update access (UPDATE)
CREATE POLICY "Allow public update access on scriptsEditor" 
    ON public."scriptsEditor" 
    FOR UPDATE 
    USING (true);

-- Allow public delete access (DELETE)
CREATE POLICY "Allow public delete access on scriptsEditor" 
    ON public."scriptsEditor" 
    FOR DELETE 
    USING (true);

-- ========================================================
-- Initial Seed Data
-- ========================================================

INSERT INTO public."scriptsEditor" (name, filename, category, description, status, locked, password, created, code, executions)
VALUES
(
    'Resume Parser',
    'resume_parser_v2.py',
    'Resume',
    'Extracts candidate skills & experience from PDF resumes using NLP pipeline.',
    'Active',
    false,
    null,
    '2024-06-15',
    'import spacy
import pdfplumber
from pathlib import Path

nlp = spacy.load("en_core_web_sm")

def parse_resume(filepath: str) -> dict:
    """Extract structured data from PDF resume."""
    with pdfplumber.open(filepath) as pdf:
        text = "\n".join(page.extract_text() or "" for page in pdf.pages)
    
    doc = nlp(text)
    skills = [ent.text for ent in doc.ents if ent.label_ in ("SKILL", "ORG")]
    
    return {
        "raw_text": text,
        "skills": list(set(skills)),
        "word_count": len(text.split()),
        "pages": len(pdf.pages)
    }

if __name__ == "__main__":
    result = parse_resume("./uploads/candidate_001.pdf")
    print(f"Parsed {result[\'pages\']} pages, found {len(result[\'skills\'])} skills")
    print(f"Skills: {\', \'.join(result[\'skills\'])}")',
    12
),
(
    'LinkedIn Crawler',
    'linkedin_crawler.py',
    'Crawler',
    'Automated LinkedIn profile data extraction with rate limiting and proxy rotation.',
    'Active',
    true,
    'admin123',
    '2024-07-22',
    'import requests
from bs4 import BeautifulSoup
import time
import random

class LinkedInCrawler:
    def __init__(self, proxy_list=None):
        self.session = requests.Session()
        self.proxies = proxy_list or []
        self.delay = (2, 5)
    
    def _get_proxy(self):
        if self.proxies:
            return {"https": random.choice(self.proxies)}
        return None
    
    def crawl_profile(self, profile_url: str) -> dict:
        """Crawl a LinkedIn profile with rate limiting."""
        time.sleep(random.uniform(*self.delay))
        resp = self.session.get(
            profile_url,
            proxies=self._get_proxy(),
            headers={"User-Agent": "Mozilla/5.0"}
        )
        soup = BeautifulSoup(resp.text, "html.parser")
        return self._extract_data(soup)

if __name__ == "__main__":
    crawler = LinkedInCrawler()
    print("LinkedIn Crawler initialized successfully")',
    8
),
(
    'AI Scoring Engine',
    'ai_scoring_engine.py',
    'AI',
    'ML-based candidate scoring using embeddings and cosine similarity matching.',
    'Active',
    false,
    null,
    '2024-08-10',
    'import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer, AutoModel
import torch

class ScoringEngine:
    def __init__(self, model_name="sentence-transformers/all-MiniLM-L6-v2"):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name)
    
    def get_embedding(self, text: str) -> np.ndarray:
        inputs = self.tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
        with torch.no_grad():
            outputs = self.model(**inputs)
        return outputs.last_hidden_state.mean(dim=1).numpy()
    
    def score(self, resume_text: str, job_desc: str) -> float:
        emb_resume = self.get_embedding(resume_text)
        emb_job = self.get_embedding(job_desc)
        return float(cosine_similarity(emb_resume, emb_job)[0][0])

if __name__ == "__main__":
    engine = ScoringEngine()
    score = engine.score("Python developer with 5 years exp", "Senior Python Engineer")
    print(f"Match Score: {score:.4f}")',
    24
),
(
    'Data Cleanup Utility',
    'data_cleanup.py',
    'Utility',
    'Batch cleanup and normalization of candidate records in the database.',
    'Disabled',
    false,
    null,
    '2024-09-05',
    'import sqlite3
import re
from datetime import datetime

def cleanup_database(db_path: str) -> dict:
    """Clean and normalize candidate records."""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    stats = {"cleaned": 0, "removed": 0, "normalized": 0}
    
    cursor.execute("SELECT id, name, email, phone FROM candidates")
    for row in cursor.fetchall():
        cid, name, email, phone = row
        clean_name = name.strip().title()
        clean_email = email.strip().lower()
        clean_phone = re.sub(r"[^0-9+]", "", phone)
        
        cursor.execute(
            "UPDATE candidates SET name=?, email=?, phone=? WHERE id=?",
            (clean_name, clean_email, clean_phone, cid)
        )
        stats["cleaned"] += 1
    
    conn.commit()
    conn.close()
    return stats

if __name__ == "__main__":
    result = cleanup_database("./data/hirenetic.db")
    print(f"Cleaned: {result[\'cleaned\']} records")',
    3
),
(
    'Resume Formatter',
    'resume_formatter.py',
    'Resume',
    'Converts raw resume text into standardized JSON format for AI processing.',
    'Active',
    false,
    null,
    '2024-10-01',
    'import json
import re
from typing import Dict, List

def format_resume(raw_text: str) -> Dict:
    """Convert raw resume text to structured JSON."""
    sections = {
        "contact": extract_contact(raw_text),
        "education": extract_education(raw_text),
        "experience": extract_experience(raw_text),
        "skills": extract_skills(raw_text),
    }
    return sections

def extract_contact(text: str) -> Dict:
    email = re.findall(r"[\w.]+@[\w.]+", text)
    phone = re.findall(r"\+?[\d\s-]{10,}", text)
    return {"email": email[0] if email else None, "phone": phone[0] if phone else None}

def extract_skills(text: str) -> List[str]:
    skill_keywords = ["python", "javascript", "react", "sql", "aws", "docker"]
    found = [s for s in skill_keywords if s.lower() in text.lower()]
    return found

if __name__ == "__main__":
    sample = "John Doe\njohn@email.com\nSkills: Python, React, AWS"
    print(json.dumps(format_resume(sample), indent=2))',
    7
),
(
    'Web Scraper Bot',
    'web_scraper_bot.py',
    'Crawler',
    'General purpose web scraper with Selenium for JavaScript-rendered pages.',
    'Disabled',
    true,
    'secure456',
    '2024-11-12',
    'from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import json

class WebScraperBot:
    def __init__(self, headless=True):
        options = webdriver.ChromeOptions()
        if headless:
            options.add_argument("--headless")
        self.driver = webdriver.Chrome(options=options)
    
    def scrape(self, url: str, selector: str) -> list:
        self.driver.get(url)
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, selector))
        )
        elements = self.driver.find_elements(By.CSS_SELECTOR, selector)
        return [el.text for el in elements]
    
    def close(self):
        self.driver.quit()

if __name__ == "__main__":
    bot = WebScraperBot()
    results = bot.scrape("https://example.com", "h1")
    print(f"Found {len(results)} elements")
    bot.close()',
    1
);
